# Site settings
title: C++ Programming
author:
  name: Shine Sujith
  email: G00414454@atu.ie
description: "A * Algorithm Report/Docs"

# Build settings
remote_theme: jekyll/minima

markdown: kramdown
kramdown:
  math_engine: mathjax